- Assets/Resources/Player.prefab
- Assets/Resources/PlayerWCam.prefab
- Assets/Resources/PlayerWCam.prefab.meta
- Assets/Scenes/SampleScene.unity
- Assets/Scenes/Scene1.unity
- Assets/Scripts/PlayerMoves.cs
- Assets/Scripts/SpawnPlayers.cs
- Assets/Textures/MinimapCameraTexture.renderTexture
- Assets/Textures/MinimapCameraTexture.renderTexture.meta
- ProjectSettings/ProjectSettings.asset
The button "quit the game" isn't working
The game physics is abstract
But the multiplayer work, so it's cool
> Fix bugs on Multiplayer and add some features

- Assets/PhysMaterial.meta
- Assets/PhysMaterial/CarChassis.physicMaterial
- Assets/PhysMaterial/CarChassis.physicMaterial.meta
- Assets/Resources/PlayerCamera.prefab
- Assets/Resources/PlayerCamera.prefab.meta
- Assets/Resources/PlayerWCam.prefab
- Assets/Scenes/Loading.unity
- Assets/Scenes/Menu.unity
- Assets/Scenes/Scene1.unity
- Assets/Scripts/CameraFollow.cs
- Assets/Scripts/CameraFollow.cs.meta
- Assets/Scripts/CarController.cs
- Assets/Scripts/GameManagerScript.cs
- Assets/Scripts/GameManagerScript.cs.meta
- Assets/Scripts/InputController.cs
- Assets/Scripts/InputController.cs.meta
- Assets/Scripts/SpawnPlayers.cs
- Assets/Scripts/WheelController.cs
- Assets/Scripts/WheelController.cs.meta
- ProjectSettings/DynamicsManager.asset
- ProjectSettings/TagManager.asset
- New system of direction
- Scalable system (number of wheels)
- Allow AI Driver
- Car can't return **without the use of freeze Z**
- Multiplayer
- Camera
- Camera Follow
- Choice for Human or AI
- Brake system
- and little things
> New system of direction 🤩 🤩 

- Assets/Scenes/Scene1.unity
Added game manager and input manager
> problems Okay, added Game and input manager

- Assets/Scenes/Scene1.unity
new track, easier to work on it
problem with camera, next thing to fix
> new track, new plane

- Assets/Car/F1 low poly.prefab
- Assets/Scenes/Scene1.unity
there is no more Cylinder with the F1 car
> Fix F1 car, not very usefull push

- Assets/Resources/PlayerWCam.prefab
- Assets/Scenes/Scene1.unity
I have froze the camera in the prefab to dev simply
> Froze cam to dev

- Assets/Scenes/Resources/PlayerCamera.prefab
- Assets/Scenes/Resources/PlayerWCam.prefab
- Assets/Scenes/Scene1.unity
> Previous camera

- Assets/Resources/PlayerWCam.prefab
- Assets/Scenes/Lobby.unity
- Assets/Scenes/Scene1.unity
- Assets/Scripts/CarController.cs
- Assets/Scripts/SpawnPlayers.cs
The spawn function doesn't work
Issue with rigibody
> Tests on SpawnPosition

- Assets/Scripts/SpawnPlayers.cs
**Don't test the game, the vehicle doesn't spawn**
> froze Instantiation

- Assets/Scenes/Lobby.unity
- Assets/Scenes/Menu.unity
- Assets/Scripts/MultiplayerScripts/MenuScript.cs
- Assets/Scripts/MultiplayerScripts/MenuScript.cs.meta
- Assets/Scripts/MultiplayerScripts/MultiplayerMenuManager.cs
- ProjectSettings/EditorBuildSettings.asset
Menu Multiplayer : Back to menu added
Scene Menu now used
Menu Button working (multiplayer and quit OK, no others wroking Bcause no scene)
> Menu modified

- Assets/Scenes/Menu.unity
Push for melvyn Bcause he can't
> Melvyn Menu push Bcause Problem

- Assets/Scenes/Scene1.unity
just need to make some corner and everything all right
> Track Limits added

- Assets/Scenes/Menu.unity
issues with format solved : was free, now 16:9  (1920:1080)
> format from free to 16:9

- Assets/Resources/PlayerWCam.prefab
The car don't jump when it spawned !
but only one car can spawn...
> Fix bug rebound

- Assets/Scripts/Race/RaceScript.cs
- Assets/Scripts/Race/RaceScript.cs.meta
> New script for race

- Assets/Scenes/Menu.unity
- Assets/Scenes/Solo.unity
- Assets/Scenes/Timer.unity
- Assets/Scenes/Timer.unity.meta
- Assets/Scripts/MenuScript.cs
- Assets/Scripts/Timer.meta
- Assets/Scripts/Timer/TimerMenu.cs
- Assets/Scripts/Timer/TimerMenu.cs.meta
- ProjectSettings/EditorBuildSettings.asset
Timer : Ok
Solo : Ok
Multiplayer : Ok
Garage : Not Ok
> Menu : Only garage

- Assets/PolygonStreetRacer/Prefabs/Vehicles/Presets/SM_Veh_Exotic_Preset_01.prefab
> Cars from Polygon working

- Assets/Scripts/PassedChekcpoints.cs
- Assets/Scripts/PassedChekcpoints.cs.meta
- Assets/Scripts/Race/TimerMode.cs
Timer Finished, Only need to change colors and it's okay
> Timer is finished

- Assets/NWH Vehicle Physics 2/_Demo/Scripts/DemoGUIController.cs
- Assets/Scripts/Race/TimerMode.cs
> Retry button and back button OK

- Assets/Prefabs/Prefabs Car/SM_Veh_Sedan_Preset_03.prefab
- Assets/Scenes/Menu.unity
Car Bug solved @Nylv_ ca bug merde !
> Car Bug Resolved

- Assets/Scenes/Garage.unity
- Assets/Scenes/Loading.unity
- Assets/Scenes/Lobby.unity
- Assets/Scenes/Menu.unity
- Assets/Scenes/Solo.unity
- Assets/Scenes/Timer.unity
updated music status to "looping" in all menus
music already added to tracks
> music looping in menus

- Assets/Scenes/Timer.unity
- Assets/Scripts/Race/PauseMenu.cs
- Assets/Scripts/Solo/SoloMenu.cs
- Assets/Scripts/Solo/SoloScript.cs
- Assets/Scripts/Timer/TimerMode.cs
-Need 2 car on City : Easy and hard AI.
-In Coming : personnal time on Timer
> Solo Mode Okay, check description

- Assets/NWH Vehicle Physics 2/Scripts/Multiplayer/Mirror.unitypackage.meta
- Assets/NWH Vehicle Physics 2/Scripts/Multiplayer/PUN2.unitypackage.meta
- Assets/Scripts/MultiplayerScripts/MultiScript.cs
- Assets/Scripts/Race/PassedCheckpoints.cs
Can Win in MT, but no loose
Synchro almost working
> Synchro almost Wroking, MT you can WIN

- Assets/NWH Vehicle Physics 2/Resources/NWH Vehicle Physics/Defaults/DefaultGearingProfile.asset
- Assets/NWH Vehicle Physics 2/Scripts/Multiplayer/Mirror.unitypackage.meta
- Assets/NWH Vehicle Physics 2/Scripts/Multiplayer/PUN2.unitypackage.meta
- Assets/Prefabs/Prefabs Car/Lambo.prefab
- Assets/Prefabs/Prefabs Car/Punto-Chantier.prefab
- Assets/Prefabs/Prefabs Car/Skyline.prefab
- Assets/Prefabs/Prefabs Car/Tesla-Not.prefab
- Assets/Resources/4x4-Mouse.prefab
- Assets/Resources/Lambo.prefab
- Assets/Resources/Punto-Chantier.prefab
- Assets/Resources/Skyline.prefab
- Assets/Resources/Tesla-Not.prefab
- Assets/Scripts/Race/CountDown.cs
- Assets/Scripts/Solo/SoloScript.cs
-IA Solo fixed
-Multi car better
> Track and multiplayer OKAY
